"""Constants which are used as dataset properties.
"""
BINARY_CLASSIFICATION = 1
MULTICLASS_CLASSIFICATION = 2
MULTILABEL_CLASSIFICATION = 3
REGRESSION = 4

DENSE = 0
SPARSE = 1
PREDICTIONS = 2
INPUT = 3

REAL_DATA = 0
POSITIVE_REAL_DATA = 1