FROM ubuntu

# System requirements
RUN apt-get update && apt-get install -y \
  build-essential \
  curl \
  python3-pip \
  swig \
  && rm -rf /var/lib/apt/lists/*

# Upgrade pip then install dependencies
RUN pip3 install --upgrade pip
RUN pip3 install git+https://github.com/automl/auto-sklearn

# Install
RUN pip3 install \
  auto-sklearn \
  jupyter
