# -*- encoding: utf-8 -*-

BINARY_CLASSIFICATION = 1
MULTICLASS_CLASSIFICATION = 2
MULTILABEL_CLASSIFICATION = 3
REGRESSION = 4

REGRESSION_TASKS = [REGRESSION]
CLASSIFICATION_TASKS = [BINARY_CLASSIFICATION, MULTICLASS_CLASSIFICATION,
                        MULTILABEL_CLASSIFICATION]

TASK_TYPES = REGRESSION_TASKS + CLASSIFICATION_TASKS

TASK_TYPES_TO_STRING = \
    {BINARY_CLASSIFICATION: 'binary.classification',
     MULTICLASS_CLASSIFICATION: 'multiclass.classification',
     MULTILABEL_CLASSIFICATION: 'multilabel.classification',
     REGRESSION: 'regression'}

STRING_TO_TASK_TYPES = \
    {'binary.classification': BINARY_CLASSIFICATION,
     'multiclass.classification': MULTICLASS_CLASSIFICATION,
     'multilabel.classification': MULTILABEL_CLASSIFICATION,
     'regression': REGRESSION}

HOLDOUT = 1
HOLDOUT_ITERATIVE_FIT = 2
CV = 3
PARTIAL_CV = 4

HOLDOUT_RESAMPLING_STRATEGIES = [HOLDOUT, HOLDOUT_ITERATIVE_FIT]

CROSS_VAL_RESAMPLING_STRATEGIES = [CV, PARTIAL_CV]

NEED_TO_REFIT_STRATEGIES = [CV, PARTIAL_CV]

RESAMPLING_STRATEGIES_TO_STRING = \
    {HOLDOUT: 'holdout',
     HOLDOUT_ITERATIVE_FIT: 'holdout-iterative-fit',
     CV: 'cv',
     PARTIAL_CV: 'partial-cv'}

STRING_TO_RESAMPLING_STRATEGIES = \
    {'holdout': HOLDOUT,
     'holdout-iterative-fit': HOLDOUT_ITERATIVE_FIT,
     'cv': CV,
     'partial-cv': PARTIAL_CV}
