name: dist-check

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - development

  pull_request:
      - master
      - development

jobs:

  dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build dist
      run: |
        python setup.py sdist

    - name: Twine check
      run: |
        pip install twine
        last_dist=$(ls -t dist/auto-sklearn-*.tar.gz | head -n 1)
        twine_output=`twine check "$last_dist"`
        if [[ "$twine_output" != "Checking $last_dist: PASSED" ]]; then echo $twine_output && exit 1;fi

    - name: Install dist
      run: |
        last_dist=$(ls -t dist/auto-sklearn-*.tar.gz | head -n 1)
        pip install $last_dist

    - name: PEP 561 Compliance
      run: |
        pip install mypy
        cd ..  # required to use the installed version of autosklearn
        if ! python -c "import autosklearn"; then exit 1; fi
