name: dist-check

on:
  # Manually triggerable in github
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - master
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    branches:
      - master
      - development

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Build dist
      run: |
        python setup.py sdist

    - name: Twine check
      run: |
        pip install twine
        last_dist=$(ls -t dist/auto-sklearn-*.tar.gz | head -n 1)
        twine check "$last_dist" --strict

    - name: Install dist
      run: |
        last_dist=$(ls -t dist/auto-sklearn-*.tar.gz | head -n 1)
        pip install $last_dist

    - name: PEP 561 Compliance
      run: |
        pip install mypy

        cd ..  # required to use the installed version of autosklearn

        # Note this doesnt perform mypy checks, only
        # that the types are exported
        if ! mypy -c "import autosklearn"; then exit 1; fi
