#https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image

on:

  push:
    branches:
      - master
      - development
      - docker_workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE_NAME: mfeurer/auto-sklearn

jobs:

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Extract branch name
        shell: bash
        run: |
          echo "Working on GITHUB_REF ${GITHUB_REF}"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker Hub
        id: meta_dockerhub
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_IMAGE_NAME }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta_dockerhub.outputs.tags }}
          labels: ${{ steps.meta_dockerhub.outputs.labels }}

      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker on Github Packages
        id: meta_githubpackages
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta_githubpackages.outputs.tags }}
          labels: ${{ steps.meta_githubpackages.outputs.labels }}

      - name: Pull Docker image from Github Packages
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$BRANCH
        env:
            BRANCH: ${{ steps.extract_branch.outputs.branch }}

      - name: Run image
        run: docker run -i -d --name unittester -v $GITHUB_WORKSPACE:/workspace -w /workspace ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$BRANCH
        env:
            BRANCH: ${{ steps.extract_branch.outputs.branch }}

      - name: Auto-Sklearn loaded
        run: docker exec  -i unittester python3 -c 'import autosklearn; print(f"Auto-sklearn imported from {autosklearn.__file__}")'

      - name: Run unit testing
        run: docker exec  -i unittester python3 -m pytest -v test
