#https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image
on:
  push:
    # Push  to `master` or `development`
    branches:
      - master
      - development
      - docker_workflow

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: automl/auto-sklearn/auto-sklearn
          tag_with_ref: true
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfeurer/auto-sklearn
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Docker Login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Pull Docker image
        run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/auto-sklearn:$BRANCH
        env:
            BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Run image
        run: docker run -i -d --name unittester -v $GITHUB_WORKSPACE:/workspace -w /workspace docker.pkg.github.com/$GITHUB_REPOSITORY/auto-sklearn:$BRANCH
        env:
            BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Auto-Sklearn loaded
        run: docker exec  -i unittester python3 -c 'import autosklearn; print(f"Auto-sklearn imported from {autosklearn.__file__}")'
      - name: Run unit testing
        run: docker exec  -i unittester python3 -m pytest -v test
