name: isort-check

on:
  # Manually triggerable in github
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - master
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    branches:
      - master
      - development

env:
  #If STRICT is set to true, it will fail on isort check fail
  STRICT: false

jobs:

  isort-format-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install isort
      run: |
        pip install isort

    - name: Run isort Check
      run: |
        isort --check-only autosklearn || ! $STRICT
