name: pre-commit

on:
  # Manually triggerable in github
  workflow_dispatch:

  # When a push occurs on either of these branches
  push:
    branches:
      - master
      - development

  # When a push occurs on a PR that targets these branches
  pull_request:
    branches:
      - master
      - development

jobs:
  run-all-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pre-commit run --all-files
