name: Regression Tests

on:

  workflow_dispatch:
    inputs:
      config:
        description: 'Config to run'
        required: true
        default: 'small.yml'

  pull_request:
    types: [labeled]

jobs:

  run-regression-tests-labeled:
    name: Run the regression tests
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch'
      || (
        github.event_name == 'pull_request'
        && github.event.action == 'labeled'
        && github.event.label.name == 'regression-tests'
      )

    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          pwd
          ls -a

      - name: Create comment
        id: create_comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello @${{ github.event.pull_request.user.login }},
            
            We are doing regression tests for

            * **Branch** ${{ github.event.pull_request.head.ref }}
            * **Commit** ${{ github.event.pull_request.head.sha }}

            [Progress and Artifacts](https://github.com/eddiebergman/auto-sklearn/actions/runs/${{ github.run_id }})

            A summary of the results will be show in this comment once complete but the full results will be available once complete.

      - name: Run Regression Tests
        id: regression_tests
        env:
          out_filename: benchmark_output.txt
        run: |
          echo "Run regressions" >> $out_filename
          echo "::set-output name=filepath::$(pwd)/$out_filename"
          # outputs:
          #   filepath: path to the results of running the PR on the benchmark

      - name: Generate Results
        id: generate_results
        env:
          out_filename: results.txt
          benchmark_path: ${{ steps.regression_tests.outputs.filepath }}
        run: |
          echo "\nResults\n" > $out_filename
          cat $benchmark_path >> $out_filename

          echo "::set-output name=filepath::$(pwd)/$out_filename"
          # outputs:
          #   filepath: path to the results of regression test vs baseline

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: |
            ${{ steps.generate_results.outputs.filepath }}
            ${{ steps.regression_tests.outputs.filepath }}
          retention-days: 1

      - name: Create Comment Body
        id: results_for_comment
        if: >
          github.event_name == 'pull_request'
          && steps.create_comment.outputs.comment-id != ''
        env:
          results_path: ${{ steps.generate_results.filepath }}
        run: |
          body="\n**Results**\n$(cat results.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
          # outputs:
          #   body: the body of the comment update

      - name: Update Comment
        id: update_comment
        if: >
          github.event_name == 'pull_request'
          && steps.create_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.create_comment.outputs.comment-id }}
          body: ${{ steps.results_for_comment.outputs.body }}
