name: Regression Tests

on:

  workflow_dispatch:
    inputs:
      config:
        description: 'Config to run'
        required: true
        default: 'small.yml'

  pull_request:
    types: [labeled]

jobs:

  run-regression-tests-labeled:
    name: Run the regression tests
    runs-on: ubuntu-latest
    if: github.event.label.name == 'regression-tests'

    steps:
      - name: DEBUG
        id: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Create comment
        id: create_comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello @${{ github.event.pull_request.user.login }}

            We are doing regrssion tests for
            - ${{ github.event.pull_request.head.ref }}${{ github.event.pull_request.head.sha }}

      - name: Run Regression Tests
        run: |
          echo "hello world"
          echo "${{ steps.create_comment.outputs.comment-id }}"

      - name: Update Comment
        id: update_comment
        if: steps.create_comment.oututs.comment-id != ''
        with:
          comment-id: ${{ steps.create_comment.output.comment-id }}
          edit-mode: append
          body: |
            success?
