name: Regression Tests
on:
  pull_request:
    types: [labeled]

jobs:
  regression-tests:
    if: contains(github.event.pull_request.labels.*.name, 'regression-tests')
    runs-on: ubuntu-latest
    steps:
      - runs: echo "hello world"
