name: Regression Tests

on:

  workflow_dispatch:
    inputs:
      config:
        description: 'Config to run'
        required: true
        default: 'small.yml'

  pull_request:
    types: [labeled]

jobs:

  run-regression-tests-labeled:
    name: Run the regression tests
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch'
      || (
        github.event.action == 'labeled'
        && github.event.label.name == 'regression-tests'
      )
    steps:
      - name: Set Env
        id: set_env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Create comment
        id: create_comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello @${{ github.event.pull_request.user.login }},
            
            We are doing regression tests for

            * **Branch** ${{ github.event.pull_request.head.ref }}
            * **Commit** ${{ github.event.pull_request.head.sha }}

            The results will be show here once complete but in the meantime,
            you can check the progress [here](https://github.com/eddiebergman/auto-sklearn/actions/runs/${{ github.run_id }}).


      - name: Run Regression Tests
        run: |
          echo "Run regressions >> results.txt"

      - name: Generate Results
        run: |
          echo "Generate results >> results.txt"

      - name: Create Comment Body
        id: results_for_comment
        if: >
          github.event_name == 'pull_request'
          && steps.create_comment.outputs.comment-id != ''
        run: |
          body="\n**Results**\n$(cat results.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body

      - name: Update Comment
        id: update_comment
        if: >
          github.event_name == 'pull_request'
          && steps.create_comment.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.create_comment.outputs.comment-id }}
          body: ${{ steps.results_for_comment.outputs.body }}

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.txt
          retention-days: 1

